#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KidHelper.Droid.Resource", IsApplication=true)]

namespace KidHelper.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int accent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int primary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int primaryDark = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int splash_background = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int window_background = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int item_thumb_size = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int guide_01 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int guide_02 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int guide_03 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int guide_04 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int guide_05 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int guide_06 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int iconweb = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090016
			public const int btnAdd = 2131296278;
			
			// aapt resource value: 0x7f090008
			public const int btnCancel = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int btnNext = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int btnPageConfig = 2131296263;
			
			// aapt resource value: 0x7f09000c
			public const int btnPlay1 = 2131296268;
			
			// aapt resource value: 0x7f090010
			public const int btnPlay2 = 2131296272;
			
			// aapt resource value: 0x7f090005
			public const int btnPrev = 2131296261;
			
			// aapt resource value: 0x7f09000d
			public const int btnRecord1 = 2131296269;
			
			// aapt resource value: 0x7f090011
			public const int btnRecord2 = 2131296273;
			
			// aapt resource value: 0x7f090009
			public const int btnSave = 2131296265;
			
			// aapt resource value: 0x7f09000b
			public const int btnSelectImage1 = 2131296267;
			
			// aapt resource value: 0x7f09000f
			public const int btnSelectImage2 = 2131296271;
			
			// aapt resource value: 0x7f090002
			public const int imageView1 = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int imageView2 = 2131296259;
			
			// aapt resource value: 0x7f090014
			public const int imgImage1 = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int imgImage2 = 2131296277;
			
			// aapt resource value: 0x7f090013
			public const int lblPos = 2131296275;
			
			// aapt resource value: 0x7f090001
			public const int linearLayout1 = 2131296257;
			
			// aapt resource value: 0x7f090004
			public const int linearLayout2 = 2131296260;
			
			// aapt resource value: 0x7f090019
			public const int mi_about = 2131296281;
			
			// aapt resource value: 0x7f090017
			public const int mi_config_pages = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int mi_guides = 2131296280;
			
			// aapt resource value: 0x7f09000e
			public const int spnColor1 = 2131296270;
			
			// aapt resource value: 0x7f090012
			public const int spnColor2 = 2131296274;
			
			// aapt resource value: 0x7f09000a
			public const int textView1 = 2131296266;
			
			// aapt resource value: 0x7f090000
			public const int webView = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Guides = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainEmpty = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PageEdit = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PageListViewItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PagesConfig = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Splash = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main_menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int about = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int guides = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int ApplicationName = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int add = 2131165185;
			
			// aapt resource value: 0x7f070016
			public const int border_color = 2131165206;
			
			// aapt resource value: 0x7f070004
			public const int cancel = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int close = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int delete = 2131165186;
			
			// aapt resource value: 0x7f07000e
			public const int dialog_page_delete_postfix = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int dialog_page_delete_text = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int dialog_page_delete_title = 2131165196;
			
			// aapt resource value: 0x7f070006
			public const int exit = 2131165190;
			
			// aapt resource value: 0x7f070014
			public const int left_side = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int need_record = 2131165202;
			
			// aapt resource value: 0x7f07000b
			public const int no_items = 2131165195;
			
			// aapt resource value: 0x7f070013
			public const int photo_error = 2131165203;
			
			// aapt resource value: 0x7f070010
			public const int record_voice = 2131165200;
			
			// aapt resource value: 0x7f070015
			public const int right_side = 2131165205;
			
			// aapt resource value: 0x7f070003
			public const int save = 2131165187;
			
			// aapt resource value: 0x7f07000f
			public const int select_photo = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int stop_record = 2131165201;
			
			// aapt resource value: 0x7f070008
			public const int title_about = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int title_edit = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int title_guides = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int title_pages_config = 2131165191;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
